// traducciones en español .ingles
const translations = {
    //objeto de idioma español 
    es: {
        title: "Inicio | Cloud Vista Lodge",
        MenuOption1: "Inicio",
        MenuOption2: "Alojamiento",
        MenuOption3: "Amenidades",
        MenuOption4: "Sobre nosotros",
        Boton01: "Reservar",
        T01: "Tu refugio en Santa María de Dota",
        T02: "Agenda tu escapada perfecta",
        T03: "Enclavado entre las montañas de Santa María de Dota, nuestro hotel ofrece una experiencia única de tranquilidad, confort y conexión con la naturaleza. Disfruta de vistas impresionantes, aire puro y una estadía diseñada para renovar cuerpo y mente.",
        Boton02: "Reservar ahora",
        T04: "Nuestro alojamiento",
        T05: "Descubre nuestras habitaciones y nuestras villas",
        T06: "Vive una experiencia única de alojamiento en nuestras acogedoras villas y elegantes suites. Cada espacio combina comodidad, privacidad y una conexión directa con la naturaleza de Santa María de Dota. Ya sea que busques relajarte junto a la chimenea o despertar con una vista espectacular, aquí encontrarás el refugio perfecto en la montaña.",
        Boton03: "Descubrir más",
        T07: "Nuestras actividades",
        T08: "Disfruta tu estadía",
        T09: "En Cloud Vista Lodge, la aventura y la naturaleza te esperan a cada paso. Disfruta de cabalgatas, caminatas guiadas, canopy y recorridos nocturnos bajo las estrellas. Ya sea que busques adrenalina o conexión con el entorno, tenemos la actividad perfecta para ti.",
        T10: "Lo que dicen nuestros huéspedes",
        T11: "Un lugar mágico, perfecto para desconectar y respirar aire puro.",
        T12: "29 años, Costa Rica",
        T13: "La vista desde nuestra villa era simplemente espectacular.",
        T14: "34 años, Argentina",
        T15: "La atención del personal fue cálida y excepcional.",
        T16: "30 años, Alemania",
        T17: "Nos sentimos como en casa, pero rodeados de montañas.",
        T18: "36 años, México",
        T19: "Cada rincón del hotel transmite paz y belleza natural.",
        T20: "22 años, España",
        T21: "Las caminatas guiadas fueron una experiencia inolvidable.",
        T22: "28 años, Estados Unidos",
        T23: "Ideal para una escapada romántica o en familia.",
        T24: "24 años, España",
        T25: "Dormir con el sonido del bosque fue maravilloso.",
        T26: "26 años, Alemania",
        T27: "Volveremos sin duda alguna, superó nuestras expectativas.",
        T28: "31 años, Italia",
        T29: "La chimenea en la habitación fue el toque perfecto.",
        T30: "37 años, Argentina",
        T31: "Santa María de Dota es un paraíso, y este hotel lo complementa perfectamente.",
        T32: "25 años, España",
        T33: "Empieza tu aventura en la montaña",
        T34: "Explora todo lo que Cloud Vista Lodge tiene para ofrecerte y reserva hoy tu estadía. Vive la experiencia de descanso, naturaleza y aventura en el corazón de Santa María de Dota. ¡Tu refugio te espera!",
        T35: 'Suscríbete y entérate de todo',
        T36: 'Recibe noticias, promociones exclusivas y consejos para tu próxima escapada a la montaña, directamente en tu correo.',
        T37: 'Ingresa tu correo electrónico',
        Boton04: 'Quiero recibir noticias',
        F01: "Ubicación",
        F02: "Santa María de Dota, San José, Costa Rica",
        F03: "Contacto",
        F04: "Teléfono: +506 2274-7625",
        F05: "E-mail: info@cloudvista.com",
        F06: "Explora",
        F07: "Alojamiento",
        F08: "Amenidades",
        F09: "Sobre nosotros",
        F10: "Contáctanos",
        F11: "Síguenos",
        F12: "Todos los derechos reservados",
        F13: "Términos y condiciones",
        empty_email: "El campo email está vacío",
        invalid_email: "Email inválido",
        success_email: "Su registro fue exitoso",
        error_email: "Error al enviar el formulario. Inténtalo de nuevo.",
        empty_title: "Espacios en blanco!",
        invalid_title: "Verifica la información",
        retry_button: "Intentar de nuevo",
    },
    //objetos de idioma ingles
    en: {
        title: "Home | Cloud Vista Lodge",
        MenuOption1: "Home",
        MenuOption2: "Accommodation",
        MenuOption3: "Amenities",
        MenuOption4: "About Us",
        Boton01: "Book now",
        T01: "Your retreat in Santa Maria de Dota",
        T02: "Plan your perfect getaway",
        T03: "Nestled among the mountains of Santa Maria de Dota, our hotel offers a unique experience of tranquility, comfort, and connection with nature. Enjoy breathtaking views, fresh air, and a stay designed to refresh your body and mind.",
        Boton02: "Book now",
        T04: "Accommodation",
        T05: "Discover our rooms and villas",
        T06: "Enjoy a unique lodging experience in our cozy villas and elegant suites. Each space combines comfort, privacy, and a direct connection with the nature of Santa María de Dota. Whether you're looking to relax by the fireplace or wake up to a spectacular view, you'll find the perfect mountain retreat here.",
        Boton03: "Discover more",
        T07: "Our Activities",
        T08: "Enjoy your stay",
        T09: "At Cloud Vista Lodge, adventure and nature await you at every turn. Enjoy horseback riding, guided hikes, zip-lining, and night tours under the stars. Whether you're seeking adrenaline or connection with the environment, we have the perfect activity for you.",
        T10: "What our guests say",
        T11: "A magical place, perfect to disconnect and breathe fresh air.",
        T12: "29 years old, Costa Rica",
        T13: "The view from our villa was simply spectacular.",
        T14: "34 years old, Argentina",
        T15: "The staff's attention was warm and exceptional.",
        T16: "30 years old, Germany",
        T17: "We felt at home, but surrounded by mountains.",
        T18: "36 years old, Mexico",
        T19: "Every corner of the hotel radiates peace and natural beauty.",
        T20: "22 years old, Spain",
        T21: "The guided hikes were an unforgettable experience.",
        T22: "28 years old, United States",
        T23: "Ideal for a romantic or family getaway.",
        T24: "24 years old, Spain",
        T25: "Sleeping with the sound of the forest was wonderful.",
        T26: "26 years old, Germany",
        T27: "We'll definitely come back, it exceeded our expectations.",
        T28: "31 years old, Italy",
        T29: "The fireplace in the room was the perfect touch.",
        T30: "37 years old, Argentina",
        T31: "Santa Maria de Dota is a paradise, and this hotel complements it perfectly.",
        T32: "25 years old, Spain",
        T33: "Start your mountain adventure",
        T34: "Explore everything Cloud Vista Lodge has to offer and book your stay today. Experience rest, nature, and adventure in the heart of Santa María de Dota. Your retreat awaits!",
        T35: 'Subscribe and stay updated',
        T36: 'Get news, exclusive promotions, and tips for your next mountain getaway delivered straight to your inbox.',
        T37: 'Enter your email address',
        Boton04: 'I want to receive updates',
        F01: "Location",
        F02: "Santa Maria de Dota, San Jose, Costa Rica",
        F03: "Contact",
        F04: "Phone: +506 2274-7625",
        F05: "E-mail: info@cloudvista.com",
        F06: "Explore",
        F07: "Accommodation",
        F08: "Amenities",
        F09: "About Us",
        F10: "Contact Us",
        F11: "Follow Us",
        F12: "All rights reserved",
        F13: "Terms and Conditions",
        empty_email: "The email field is empty",
        invalid_email: "Invalid email",
        success_email: "Subscription successful",
        error_email: "There was an error sending the form. Please try again.",
        empty_title: "Empty spaces!",
        invalid_title: "Verify the information",
        retry_button: "Try again",
    }
};

//funcion para cambiar el idioma

function changeLanguage() {
    //conversion del lenguaje html
    const lang = document.documentElement.lang === 'es' ? 'en' : 'es';
    document.documentElement.lang = lang;

    //cambiar texto de los elementos con data-translate
    document.querySelectorAll('[data-translate]').forEach(element => {
        //asignacion de atributo data-translate
        const key = element.getAttribute('data-translate');
        //elementos html sean traducidos por la llaves lang - key
        element.innerHTML = translations[lang][key];
    });

    // Traducir placeholders
    document.querySelectorAll('[data-translate-placeholder]').forEach(element => {
        const key = element.getAttribute('data-translate-placeholder');
        if (translations[lang][key]) {
            element.placeholder = translations[lang][key];
        }
    });
}